Publish test report

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -18,6 +18,12 @@ jobs:
       - name: Test
         run: |
           ./gradlew clean build test -PvideoArch=linux -i
+      - name: Publish Test Report
+        uses: actions/upload-artifact@v3
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results-html
+          path: ./build/reports/tests/test/
       - name: Build Application JARs
         run: |
           ./gradlew clean
